import { useCallback } from 'react';
import { translations } from '../../../config/translations.js';
import { themes } from '../../../config/themes.js';
import useWorkspaceState from '../state/useWorkspaceState.js';
import useWorkspaceFilters from '../state/useWorkspaceFilters.js';
import useSidebarCollections from '../state/useSidebarCollections.js';
import useWorkspaceUiInteractions from '../state/useWorkspaceUiInteractions.js';
import useWorkspaceCellHelpers from '../state/useWorkspaceCellHelpers.jsx';
import useWorkspaceColumnTypeHelpers from '../state/useWorkspaceColumnTypeHelpers.js';
import useWorkspaceCommandPalette from '../state/useWorkspaceCommandPalette.js';
import useWorkspacePersistenceEffects from '../state/useWorkspacePersistenceEffects.js';
import useWorkspaceSqlDialectHelpers from '../state/useWorkspaceSqlDialectHelpers.js';
import useWorkspaceNotifications from '../state/useWorkspaceNotifications.js';
import useWorkspaceImportLoaders from '../state/useWorkspaceImportLoaders.js';

export default function useDatabaseManagerFoundationModel() {
  const workspace = useWorkspaceState();
  const { loadJsZip, loadXlsx } = useWorkspaceImportLoaders();

  const t = useCallback((key) => translations[workspace.lang][key] || key, [workspace.lang]);
  const currentTableData =
    workspace.activeDb && workspace.activeTable
      ? workspace.databases[workspace.activeDb]?.[workspace.activeTable]
      : null;
  const tc = themes[workspace.theme];
  const baseFieldClass = `w-full bg-[#18181b] border border-[#3a3a3f] rounded-md py-2 px-3 text-sm text-zinc-100 transition-colors disabled:opacity-50 shadow-[inset_0_1px_0_rgba(255,255,255,0.03)] ${tc.focusRing}`;
  const baseSelectClass = `${baseFieldClass} appearance-none`;
  const baseTextAreaClass = `${baseFieldClass} resize-y min-h-[120px]`;

  const workspaceColumnTypeHelpers = useWorkspaceColumnTypeHelpers({
    formData: workspace.formData,
  });
  const { isAutoGeneratedColumn, isBooleanColumn, isNumericColumnType } =
    workspaceColumnTypeHelpers;

  useWorkspacePersistenceEffects({
    lang: workspace.lang,
    theme: workspace.theme,
    settings: workspace.settings,
    sqlHistory: workspace.sqlHistory,
    sqlSnippets: workspace.sqlSnippets,
    sidebarWidth: workspace.sidebarWidth,
    pinnedItems: workspace.pinnedItems,
    savedConnections: workspace.savedConnections,
    databaseVisibility: workspace.databaseVisibility,
    openTableTabs: workspace.openTableTabs,
    activeTableTabId: workspace.activeTableTabId,
    pinnedColumnsByTable: workspace.pinnedColumnsByTable,
    columnOrderByTable: workspace.columnOrderByTable,
  });

  const { currentDriver, quoteIdentifier, escapeLiteral } = useWorkspaceSqlDialectHelpers(
    workspace.connForm,
  );

  const { handleSidebarResizeStart, handleSplitterMouseDown } = useWorkspaceUiInteractions({
    ...workspace,
  });

  const workspaceFilters = useWorkspaceFilters({
    ...workspace,
    t,
    currentTableData,
  });

  const workspaceSidebarCollections = useSidebarCollections({ ...workspace });

  const { filteredCommands, hasSidebarFilters } = useWorkspaceCommandPalette({ ...workspace });

  const workspaceCellHelpers = useWorkspaceCellHelpers({ lang: workspace.lang });

  const { showToast, copyToClipboard } = useWorkspaceNotifications({
    setToasts: workspace.setToasts,
    t,
  });

  return {
    workspace,
    t,
    tc,
    themes,
    currentTableData,
    baseFieldClass,
    baseSelectClass,
    baseTextAreaClass,
    currentDriver,
    quoteIdentifier,
    escapeLiteral,
    handleSidebarResizeStart,
    handleSplitterMouseDown,
    workspaceFilters,
    workspaceSidebarCollections,
    filteredCommands,
    hasSidebarFilters,
    workspaceCellHelpers,
    workspaceColumnTypeHelpers,
    isAutoGeneratedColumn,
    isBooleanColumn,
    isNumericColumnType,
    showToast,
    copyToClipboard,
    loadJsZip,
    loadXlsx,
  };
}
