import useWorkspaceSqlActions from '../actions/useWorkspaceSqlActions.js';
import useWorkspaceDataActions from '../actions/useWorkspaceDataActions.js';
import useWorkspaceImportExportActions from '../actions/useWorkspaceImportExportActions.js';
import useWorkspaceNavigationActions from '../actions/useWorkspaceNavigationActions.js';
import useWorkspaceTableCellRenderer from '../state/useWorkspaceTableCellRenderer.jsx';
import useWorkspaceTableViewState from '../state/useWorkspaceTableViewState.js';

export default function useDatabaseManagerWorkspaceActionsModel(model, apiModel) {
  const {
    workspace,
    t,
    tc,
    themes,
    currentTableData,
    baseFieldClass,
    baseSelectClass,
    baseTextAreaClass,
    currentDriver,
    quoteIdentifier,
    escapeLiteral,
    handleSidebarResizeStart,
    handleSplitterMouseDown,
    workspaceFilters,
    workspaceSidebarCollections,
    filteredCommands,
    hasSidebarFilters,
    workspaceCellHelpers,
    workspaceColumnTypeHelpers,
    isAutoGeneratedColumn,
    isBooleanColumn,
    isNumericColumnType,
    showToast,
    copyToClipboard,
    loadJsZip,
    loadXlsx,
  } = model;
  const {
    callApi,
    buildConnectionPayload,
    executeSql,
    executeSqlTransactionBatch,
    getFirstValue,
    refreshSchemas,
    ensureDatabaseTablesLoaded,
    refreshActiveTable,
    refreshPing,
  } = apiModel;
  const { getCellTextValue, isJsonColumn, parseJsonCellValue } = workspaceCellHelpers;

  const workspaceNavigationActions = useWorkspaceNavigationActions({
    ...workspace,
    t,
    showToast,
    currentTableData,
    refreshActiveTable,
    refreshSchemas,
    ensureDatabaseTablesLoaded,
    refreshPing,
    executeSql,
    quoteIdentifier,
    escapeLiteral,
    parseJsonCellValue,
    isJsonColumn,
  });
  const { selectDbAndTable } = workspaceNavigationActions;

  const workspaceSqlActions = useWorkspaceSqlActions({
    ...workspace,
    executeSql,
    executeSqlTransactionBatch,
    getFirstValue,
    refreshSchemas,
    ensureDatabaseTablesLoaded,
    refreshActiveTable,
    showToast,
    t,
    currentDriver,
  });

  const workspaceTableViewState = useWorkspaceTableViewState({
    ...workspace,
    currentTableData,
    currentDriver,
    copyToClipboard,
    getCellTextValue,
    clearAllColumnFilters: workspaceFilters.clearAllColumnFilters,
  });
  const { processedData } = workspaceTableViewState;

  const workspaceImportExportActions = useWorkspaceImportExportActions({
    ...workspace,
    t,
    loadJsZip,
    loadXlsx,
    currentTableData,
    isAutoGeneratedColumn,
    isBooleanColumn,
    isNumericColumnType,
    quoteIdentifier,
    escapeLiteral,
    callApi,
    buildConnectionPayload,
    executeSql,
    refreshSchemas,
    ensureDatabaseTablesLoaded,
    refreshActiveTable,
    showToast,
    processedData,
  });

  const dataActions = useWorkspaceDataActions({
    ...workspace,
    currentTableData,
    currentDriver,
    executeSql,
    refreshActiveTable,
    refreshSchemas,
    ensureDatabaseTablesLoaded,
    selectDbAndTable,
    quoteIdentifier,
    escapeLiteral,
    showToast,
    t,
  });

  const {
    saveInlineEdit: saveInlineEditRaw,
    handleBulkDelete: handleBulkDeleteRaw,
    ...otherDataActions
  } = dataActions;

  const saveInlineEdit = (editingCell = workspace.editingCell) => saveInlineEditRaw(editingCell);
  const handleBulkDelete = (selectedRows = workspace.selectedRows) =>
    handleBulkDeleteRaw(selectedRows);
  const renderCellContent = useWorkspaceTableCellRenderer({
    tc,
    isJsonColumn,
    getCellTextValue,
  });

  const workspaceInputs = {
    ...workspace,
    t,
    tc,
    themes,
    currentTableData,
    currentDriver,
    executeSql,
    quoteIdentifier,
    escapeLiteral,
    baseFieldClass,
    baseSelectClass,
    baseTextAreaClass,
    ensureDatabaseTablesLoaded,
    handleSidebarResizeStart,
    handleSplitterMouseDown,
    filteredCommands,
    hasSidebarFilters,
    showToast,
    copyToClipboard,
    renderCellContent,
    ...workspaceSidebarCollections,
    ...workspaceFilters,
    ...workspaceTableViewState,
    ...workspaceNavigationActions,
    ...workspaceSqlActions,
    ...workspaceImportExportActions,
    ...otherDataActions,
    ...workspaceCellHelpers,
    ...workspaceColumnTypeHelpers,
    saveInlineEdit,
    handleBulkDelete,
  };

  return { workspaceInputs };
}
